config/routes.rb
Rails.application.routes.draw do

concern :commentable do 
  resources :comments
end
get 'welcome/index'
 

root 'welcome#index'
  
get 'adoption/p/:id' => 'posts#adoption', as: :adoption
get 'found/p/:id' => 'posts#found', as: :found
get 'missing/p/:id' => 'posts#missing', as: :missing
  
post 'login' => 'session#login'
get 'logout'=> 'session#logout'
  
resources :users, except:[:edit, :update]
get 'user/edit'=> 'users#edit'
patch 'user/update'=> 'users#update'
get 'mps'=> 'users#messages'
  
resources :posts, concerns: :commentable

resources :memes, except:[:index], concerns: :commentable
get 'moderation' => 'memes#moderation'
post 'vote' => 'memes#vote', as: :vote
get 'meme/p/:id' => 'memes#index', as: :meme_list

get 'mp/:id' => 'messages#new', as: :mp
get 'messages' => 'messages#show'
post 'messages' => 'messages#create'

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  
  
  
  def login
    user = User.find_by_email(params[:email])
    if user and user.authenticate(params[:password])
      session[:user_id]=user.id
    end
    redirect_to :back
  end
  
  def logout
    session[:user_id]=nil
    redirect_to :back
  end
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/session/_header.html.erb
<div class="header">
<%=form_tag action:'login', controller: 'session' do %>
<ul>
  <li>
    <%= link_to 'PetProject', root_path, class:'logo'%>
  </li>
  <li>
    <%= link_to 'Adoption', adoption_path(1)%>
  </li>
  <li>
    <%= link_to 'Missing', missing_path(1)%>
  </li>
  <li>
    <%= link_to 'Found', found_path(1)%>
  </li>
  <li>
    <%= link_to 'Memes', meme_list_path(1)%>
  </li>
  
  <div style="width:auto;float:right;">
  <% if loged? %>
  
    <li>
      <%= link_to 'Logout', logout_path, style:"vertical-align:middle"%>
    </li>

    <li class="profile-picture">
      <%= link_to (image_tag current_user.avatar.url(:thumb)), user_edit_path, style:"vertical-align:middle"%>
    </li>
    
  <% else %>
    <li>
    <%= link_to 'Sign up', new_user_path %>
    </li>
    <li>
      Email: <%= email_field_tag :email, '' ,class: "form_field" %>
    </li>
    
    <li>
      Password: <%= password_field_tag :password, '' ,class: "form_field"  %>
    </li>
    
    <li>
      <%=submit_tag :Login, class: "form_button"  %>
    </li>
    <% end %>
    </div>
</ul>
<% end %>
</div>