config/routes.rb
Rails.application.routes.draw do

concern :commentable do 
  resources :comments
end
get 'welcome/index'
 

root 'welcome#index'
  
get 'adoption/p/:id' => 'posts#adoption', as: :adoption
get 'found/p/:id' => 'posts#found', as: :found
get 'missing/p/:id' => 'posts#missing', as: :missing
  
post 'login' => 'session#login'
get 'logout'=> 'session#logout'
  
resources :users, except:[:edit, :update]
get 'user/edit'=> 'users#edit'
patch 'user/update'=> 'users#update'
get 'mps'=> 'users#messages'
  
resources :posts, concerns: :commentable

resources :memes, except:[:index], concerns: :commentable
get 'moderation' => 'memes#moderation'
post 'vote' => 'memes#vote', as: :vote
get 'meme/p/:id' => 'memes#index', as: :meme_list

get 'mp/:id' => 'messages#new', as: :mp
get 'messages' => 'messages#show'
post 'messages' => 'messages#create'

end

app/models/meme.rb
class Meme < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :moderators, class_name: 'User'
  has_many :comments
  has_attached_file :body, styles: { large: "1000x",medium:"600x",small: "200x200>"}, default_url: "/images/:style/missing.png"
  
  validates_attachment_content_type :body, content_type: /\Aimage\/.*\Z/
  validates :title, presence:true, length:{maximum:25}
  validates :body, attachment_presence:true
  
  before_save :accepted?
  
  
  private
    def accepted?
      if self.status == 'In Moderation' and self.vote_count >= 1 and self.vote.to_f/self.vote_count >= 0.5
        self.status='Accepted'
      end
    end
end

app/controllers/memes_controller.rb
class MemesController < ApplicationController
  before_action :set_meme, only:[:show,:positive_vote,:negative_vote,:neutral_vote]
  def new
    @meme = Meme.new
  end
  
  def create
    @meme = Meme.new(meme_params)
    @meme.user_id=session[:user_id]
    if @meme.save
      redirect_to meme_path(@meme)
    else
      render 'new'
    end
  end
  
  def show
    @comment=Comment.new
    @comments=Comment.where(meme_id: @meme.id)
  end
  
  def index
    memes=Meme.where(status: 'Accepted')
    @page=paginator(memes,params[:id])
    set_next_previous(memes,params[:id])
  end
  
  def vote
    @meme=Meme.find(params[:id])
    @meme.moderators << current_user
    @meme.vote+=params[:point].to_i
    @meme.vote_count+=1
    @meme.save
    
    redirect_to moderation_path
  end
  
  def moderation
    memes=[]
    memes_in_moderation = Meme.where(status: 'In Moderation')
    memes_in_moderation.each do |meme|
      unless current_user.moderated_memes.include?(meme)
        memes << meme
      end
    end
    @meme=memes.first
  end
  
  private
    def meme_params
      params.require(:meme).permit(:body,:title)
    end
  
   def set_meme
     @meme=Meme.find(params[:id])
   end

end

app/helpers/memes_helper.rb
module MemesHelper
end

app/views/memes/index.html.erb
<%if @page%>
  <%@page.each do |meme| %>
    <h2><%=link_to meme.title+" by: #{meme.user.name}", meme_path(meme) %></h2>
<%= link_to image_tag(meme.body.url(:medium)), meme_path(meme) %>
  <% end %>
<%else %>
  <h2>Sorry, there are no approved memes yet...</h2>
  <p>But you can help us going to <b><%=link_to 'Moderation', moderation_path%></b></p>
<% end %>
<% if @next_page %>
  <%=link_to 'Next page', meme_list_path(@next_page)%>
<%end%>
<% if @previous_page%>
  <%=link_to 'Previous page', meme_list_path(@previous_page)%>
<%end%>

app/views/memes/moderation.html.erb
<%if @meme%>
  <h2><%=@meme.title%></h2>
  <%= image_tag @meme.body.url(:large) %>
  <p><%=button_to 'Accept', vote_path, params:{id:@meme.id,point:1}%>  <%=button_to 'Pass', vote_path, params:{id:@meme.id,point:0}%> <%=button_to 'Decline', vote_path, params:{id:@meme.id,point: -1}%></p>
<% else %>
  <h2>Currently, there are not memes to moderate</h2>
<% end %>

app/views/memes/new.html.erb
<%if @meme.errors.any? %>
  <%@meme.errors.full_messages.each do |message|%>
    <p><%=message %></p>
  <%end%>
<%end%>

<%= form_for @meme, html: {multipart: true} do |f| %>
  <%= f.text_field :title %>
  <%= f.file_field :body %>
  <%= f.submit :create %>
<% end %>

app/views/memes/show.html.erb
<h2><%=@meme.title %> by: <%=link_to @meme.user.name, user_path(@meme.user_id)%></h2>
<div>
  <%= image_tag @meme.body.url(:large) %>
</div>


<div>
  <%if @comments%>
    <% @comments.each do |comment| %>
      <%=User.find(comment.user_id).name%>
      <%=comment.body%>
    <% end %>
  <% end %>
</div>

<div>
  <% if loged? %>
    <%= form_for [@meme,@comment] do |f| %>
      Body:<%=f.text_area :body %>
      <%= f.submit :send %>
    <%end%>
  <%else%>
    <p>You need to log in before comment</p>
  <%end%>
</div>