config/routes.rb
Rails.application.routes.draw do

concern :commentable do 
  resources :comments
end
get 'welcome/index'
 

root 'welcome#index'
  
get 'adoption/p/:id' => 'posts#adoption', as: :adoption
get 'found/p/:id' => 'posts#found', as: :found
get 'missing/p/:id' => 'posts#missing', as: :missing
  
post 'login' => 'session#login'
get 'logout'=> 'session#logout'
  
resources :users, except:[:edit, :update]
get 'user/edit'=> 'users#edit'
patch 'user/update'=> 'users#update'
get 'mps'=> 'users#messages'
  
resources :posts, concerns: :commentable

resources :memes, except:[:index], concerns: :commentable
get 'moderation' => 'memes#moderation'
post 'vote' => 'memes#vote', as: :vote
get 'meme/p/:id' => 'memes#index', as: :meme_list

get 'mp/:id' => 'messages#new', as: :mp
get 'messages' => 'messages#show'
post 'messages' => 'messages#create'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_attached_file :avatar, styles: {medium: "300x300>", small: "100x100>",thumb: "60x60>"}, default_url: "/images/:style/missing.png"
  validates :email, presence:true, uniqueness: true, length:{minimum:9,maximum:200}
  validates :name, presence:true, length:{maximum:15}
  has_many :posts
  has_many :comments
  has_many :sent_messages, class_name: 'Message'
  has_many :received_messages, class_name: 'Message'
  has_many :memes
  has_and_belongs_to_many :moderated_memes, class_name: 'Meme'
  validates_attachment_content_type :avatar, content_type: /\Aimage/
  validates_attachment_file_name :avatar, matches: [/png\Z/, /jpe?g\Z/]
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only:[:show]
  before_action :is_loged?, only:[:messages,:edit,:show,:update]
  def new
    @user=User.new
  end
  
  def create
    @user=User.new(user_params)
    if @user.save
      redirect_to root_path
    else
      render 'new'
    end    
  end
  
  def show
    
  end
  
  def messages
    @user= current_user
    @sent_msgs=Message.where(sender_id:@user.id)
    @received_msgs=Message.where(recipent_id:@user.id)
  end
  
  def edit
    @user=current_user
  end
  
  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render 'edit'
    end
  end
  
  private
    def user_params
      params.require(:user).permit(:password,:password_confirmation,:name,:email,:avatar)
    end
  
    def edit_params
      params.require(:user).permit(:password,:password_confirmation,:avatar)
    end
    
    def set_user
      @user=User.find(params[:id])
    end
  
    def current_user
      User.find(session[:user_id])  
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= form_for @user, url: user_update_path, html:{multipart:true} do |f| %>
  Picture <%=f.file_field :avatar%>
  Password <%= f.password_field :password %>
  Password Confirmation<%= f.password_field :password_confirmation %>
  <%=f.submit %>
<%end%>

app/views/users/messages.html.erb
<h2>Messages</h2>

<h3>Received</h3>
<%@received_msgs.each do |msg| %>
  <p><%=msg.sender.name%>:</p>
  <p><%=msg.body%></p>
<% end %>

<h3>Sent</h3>
<%@sent_msgs.each do |msg| %>
  <p><%=msg.recipent.name %>:</p>
  <p><%=msg.body%></p>
<% end %>

app/views/users/new.html.erb
<div style='background-color:red;color:white'>
  <% if @user.errors.any? %>
   <% @user.errors.full_messages.each do |message|%>
    <p><%= message %></p>
   <%end%>
  <%end%>
</div>
<%= form_for @user,url: users_path, html:{multipart:true} do |f| %>
<ul style="list-style-type:none; color:#2A2C2B">
  <li style="padding:5px">
  Name: <%=f.text_field :name, class: "form_field" %>
  </li>
  <li style="padding:5px">
  Email: <%=f.text_field :email, class: "form_field"  %>
  </li>
  <li style="padding:5px">
  Password: <%=f.password_field :password, class: "form_field"  %>
  </li>
  <li style="padding:5px">
  Password confirmation: <%=f.password_field :password_confirmation, class: "form_field"  %>
  </li>
  <li style="padding:5px">
  Avatar: <%=f.file_field :avatar, class: "form_field"  %>
  </li>
  <li style="padding:5px">
  <%=f.submit :send, class: "form_button" %>
  </li>
</ul>
<%end%>

app/views/users/show.html.erb
<h2>This is <%=@user.name%>'s profile</h2>
<p>Email:<%=@user.email%></p>
<p><%= link_to 'Send private message', mp_path(@user.id) %></p>
<h3><%= @user.name%>'s posts</h3>
<% @user.posts.each do |post| %>
  <h4><%=link_to post.title, post_path(post)%> </h4>
<% end %>