config/routes.rb
Rails.application.routes.draw do

concern :commentable do 
  resources :comments
end
get 'welcome/index'
 

root 'welcome#index'
  
get 'adoption/p/:id' => 'posts#adoption', as: :adoption
get 'found/p/:id' => 'posts#found', as: :found
get 'missing/p/:id' => 'posts#missing', as: :missing
  
post 'login' => 'session#login'
get 'logout'=> 'session#logout'
  
resources :users, except:[:edit, :update]
get 'user/edit'=> 'users#edit'
patch 'user/update'=> 'users#update'
get 'mps'=> 'users#messages'
  
resources :posts, concerns: :commentable

resources :memes, except:[:index], concerns: :commentable
get 'moderation' => 'memes#moderation'
post 'vote' => 'memes#vote', as: :vote
get 'meme/p/:id' => 'memes#index', as: :meme_list

get 'mp/:id' => 'messages#new', as: :mp
get 'messages' => 'messages#show'
post 'messages' => 'messages#create'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @adoptions= Post.where(category: "Adoption").order('created_at DESC').first(10)
    @founds = Post.where(category: "Found").order('created_at DESC').first(10)
    @missings = Post.where(category: "Missing").order('created_at DESC').first(10)
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<div class="index">
  
  <%list=[@adoptions,@missings,@founds]%>
  
  <%for i in list%>
  
    <%if i[0] %>
      <%case i[0].category%>
      <%when 'Missing'%>
        <h2><%=link_to 'Missing pets', missing_path(1)%></h2>
      <%when 'Adoption'%>
        <h2><%=link_to 'Pets for adoption', adoption_path(1)%></h2>
      <%else%>
        <h2><%=link_to 'Found pets', found_path(1)%></h2>
      <%end%>
      <table>
      <tr>
      <%i.each do |post|%>
        <td>
        <%=link_to (image_tag post.cover.url(:thumb)), post_path(post)%>
        </td>
      <%end%> 
      </tr>
      </table>
    <%else%>
      <h3>There are no posts that belong to this category</h3>
    <%end%>
  <%end%>
  
</div>